# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_text = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_text.setMinimumSize(QtCore.QSize(0, 29))
        self.lineEdit_text.setObjectName("lineEdit_text")
        self.horizontalLayout.addWidget(self.lineEdit_text)
        self.checkBox_addhttp = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_addhttp.setMinimumSize(QtCore.QSize(136, 0))
        self.checkBox_addhttp.setObjectName("checkBox_addhttp")
        self.horizontalLayout.addWidget(self.checkBox_addhttp)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_timeout = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_timeout.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_timeout.setObjectName("comboBox_timeout")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_timeout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_type = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_type.setMinimumSize(QtCore.QSize(84, 29))
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_type)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.spinBox_num = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_num.setMinimumSize(QtCore.QSize(40, 29))
        self.spinBox_num.setMaximumSize(QtCore.QSize(46, 16777215))
        self.spinBox_num.setMinimum(1)
        self.spinBox_num.setObjectName("spinBox_num")
        self.horizontalLayout_5.addWidget(self.spinBox_num)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_save.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_4.addWidget(self.pushButton_save)
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_4.addWidget(self.pushButton_start)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_result.setMinimumSize(QtCore.QSize(0, 200))
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout_2.addWidget(self.textEdit_result)
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_log.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        self.verticalLayout_2.addWidget(self.textEdit_log)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 26))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_update = QtWidgets.QMenu(self.menubar)
        self.menu_update.setObjectName("menu_update")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionKEY = QtWidgets.QAction(MainWindow)
        self.actionKEY.setObjectName("actionKEY")
        self.action_start = QtWidgets.QAction(MainWindow)
        self.action_start.setObjectName("action_start")
        self.action_clean = QtWidgets.QAction(MainWindow)
        self.action_clean.setObjectName("action_clean")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_update = QtWidgets.QAction(MainWindow)
        self.action_update.setObjectName("action_update")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu_1.addAction(self.actionKEY)
        self.menu_2.addAction(self.action_start)
        self.menu_2.addAction(self.action_clean)
        self.menu_2.addAction(self.action_save)
        self.menu_update.addAction(self.action_update)
        self.menu_update.addAction(self.action_about)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_update.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "漏洞目标采集工具 by qianxiao996"))
        self.groupBox.setTitle(_translate("MainWindow", "采集设置"))
        self.label.setText(_translate("MainWindow", "关键字"))
        self.label_2.setText(_translate("MainWindow", "接  口"))
        self.checkBox_addhttp.setText(_translate("MainWindow", "自动增加HTTP头"))
        self.label_4.setText(_translate("MainWindow", "超时"))
        self.comboBox_timeout.setItemText(0, _translate("MainWindow", "10"))
        self.comboBox_timeout.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_timeout.setItemText(2, _translate("MainWindow", "15"))
        self.comboBox_timeout.setItemText(3, _translate("MainWindow", "20"))
        self.comboBox_timeout.setItemText(4, _translate("MainWindow", "30"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "FOFA"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Shodan"))
        self.comboBox_type.setItemText(2, _translate("MainWindow", "Censys"))
        self.comboBox_type.setItemText(3, _translate("MainWindow", "ZoomEye"))
        self.label_3.setText(_translate("MainWindow", "页数"))
        self.pushButton_save.setText(_translate("MainWindow", "保存结果"))
        self.pushButton_start.setText(_translate("MainWindow", "开始获取"))
        self.menu_1.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "选项"))
        self.menu_update.setTitle(_translate("MainWindow", "其他"))
        self.action.setText(_translate("MainWindow", "设置"))
        self.actionKEY.setText(_translate("MainWindow", "KEY"))
        self.action_start.setText(_translate("MainWindow", "开始获取"))
        self.action_clean.setText(_translate("MainWindow", "清空数据"))
        self.action_save.setText(_translate("MainWindow", "保存结果"))
        self.action_update.setText(_translate("MainWindow", "程序更新"))
        self.action_about.setText(_translate("MainWindow", "关于作者"))

